### ISSUE TITLE
readme file

### ISSUE THREAD

**Issue by tjhubert** [uiuc-web-programming/mp2_starter#8]
```bash
git clone --bare https://github.com/uiuc-web-programming/mp2_starter.git
cd mp2_starter.git
git push --mirror https://github.com/your-github-username/mp2.git
cd ..
rm -rf mp2_starter.git

# should be https://github.com/your-github-username/mp2.git
git clone https://github.com/uiuc-web-programming/mp2_starter.git 
 # should be mp2 instead of mp2_starter
cd mp2_starter
npm install
bower install
grunt compass
grunt uglify
grunt
```

**Comment by tjhubert** [comment]
current:
Also, if you have problems debugging your JavaScript due to uglification, you can disable it by commenting out line 46 of gruntfile.js and uncommenting line 47.

should be:
Also, if you have problems debugging your JavaScript due to uglification, you can disable it by commenting out line 47 of gruntfile.js and uncommenting line 48.

**Comment by sskhandek** [comment]
You rock! Thanks for pointing it out :+1:
